# Generated by Django 4.1.3 on 2022-11-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_name', models.CharField(blank=True, max_length=50, null=True)),
                ('marker_des', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
            ],
        ),
    ]
