# Generated by Django 4.1.3 on 2022-11-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='lang',
            new_name='marker_lat',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='lat',
            new_name='marker_lng',
        ),
    ]
